export type * from './Page.Aside.types'
export type * from './Page.Footer.types'
export type * from './Page.Header.types'
export type * from './Page.Main.types'
export type * from './Page.Page.types'
